export const TYPOGRAPHY = {
  HeadEnBold26: {
    fontFamily: 'Hyundai Sans Head,sans-serif',
    fontSize: '26px',
    fontWeight: 700,
    lineHeight: '36px',
    letterSpacing: '-0.01em',
  },
  HeadENBold24: {
    fontFamily: 'Hyundai Sans Head,sans-serif',
    fontSize: '24px',
    fontWeight: 700,
    lineHeight: '32px',
    letterSpacing: '-0.01em',
  },
  HeadENBold22: {
    fontFamily: 'Hyundai Sans Head,sans-serif',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: '28px',
    letterSpacing: '-0.01em',
  },
  HeadENMedium20: {
    fontFamily: 'Hyundai Sans Head,sans-serif',
    fontSize: '20px',
    fontWeight: 500,
    lineHeight: '28px',
    letterSpacing: '-0.01em',
  },
  HeadENBold10: {
    fontFamily: 'Hyundai Sans Head,sans-serif',
    fontSize: '10px',
    fontWeight: 700,
    lineHeight: '12px',
    letterSpacing: '-0.01em',
  },

  TextENMedium18: {
    fontFamily: 'Hyundai Sans Text,sans-serif',
    fontSize: '18px',
    fontWeight: 500,
    lineHeight: '28px',
    letterSpacing: '-0.01em',
  },
  TextENMedium16: {
    fontFamily: 'Hyundai Sans Text,sans-serif',
    fontSize: '16px',
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: '-0.01em',
  },
  TextENMedium14: {
    fontFamily: 'Hyundai Sans Text,sans-serif',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '22px',
    letterSpacing: '-0.01em',
  },
  CaptionENMedium14: {
    fontFamily: 'Hyundai Sans Text,sans-serif',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '28px',
    letterSpacing: '-0.01em',
  },
  CaptionENMedium12: {
    fontFamily: 'Hyundai Sans Text,sans-serif',
    fontSize: '12px',
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: '-0.01em',
  },

  HeadKRBold32: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '32px',
    fontWeight: 700,
    lineHeight: '36px',
    letterSpacing: '-0.03em',
  },
  HeadKRBold26: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '26px',
    fontWeight: 700,
    lineHeight: '36px',
    letterSpacing: '-0.03em',
  },
  HeadKRBold24: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '24px',
    fontWeight: 700,
    lineHeight: '32px',
    letterSpacing: '-0.03em',
  },
  HeadKRBold22: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '22px',
    fontWeight: 700,
    lineHeight: '28px',
    letterSpacing: '-0.03em',
  },
  HeadKRBold20: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '20px',
    fontWeight: 700,
    lineHeight: '24px',
    letterSpacing: '-0.03em',
  },
  HeadKRBold18: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '18px',
    fontWeight: 700,
    lineHeight: '28px',
    letterSpacing: '-0.03em',
  },
  HeadKRBold12: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: '18px',
  },

  TextKRBold12: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },

  HeadKRMedium26: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '26px',
    fontWeight: 500,
    lineHeight: '36px',
    letterSpacing: '-0.03em',
  },
  HeadKRMedium24: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '24px',
    fontWeight: 500,
    lineHeight: '32px',
    letterSpacing: '-0.03em',
  },
  HeadKRMedium22: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '22px',
    fontWeight: 500,
    lineHeight: '28px',
    letterSpacing: '-0.03em',
  },
  HeadKRMedium20: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '20px',
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: '-0.03em',
  },
  HeadKRMedium18: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '18px',
    fontWeight: 500,
    lineHeight: '28px',
    letterSpacing: '-0.03em',
  },
  HeadKRMedium16: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '16px',
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: '-0.03em',
  },
  HeadKRMedium14: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '22px',
    letterSpacing: '-0.03em',
  },

  TextKRMedium18: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '18px',
    fontWeight: 500,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },
  TextKRMedium16: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '16px',
    fontWeight: 500,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },
  TextKRMedium14: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '22px',
    letterSpacing: '-0.03em',
  },
  TextKRMedium12: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '12px',
    fontWeight: 500,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },
  TextKRMedium10: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '10px',
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: '-0.03em',
  },

  HeadKRRegular26: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '26px',
    fontWeight: 400,
    lineHeight: '36px',
    letterSpacing: '-0.03em',
  },
  HeadKRRegular24: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '24px',
    fontWeight: 400,
    lineHeight: '32px',
    letterSpacing: '-0.03em',
  },
  HeadKRRegular22: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '22px',
    fontWeight: 400,
    lineHeight: '28px',
    letterSpacing: '-0.03em',
  },
  HeadKRRegular20: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '20px',
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: '-0.03em',
  },

  TextKRRegular18: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '18px',
    fontWeight: 400,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },
  TextKRRegular16: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '16px',
    fontWeight: 400,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },
  TextKRRegular14: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: '22px',
    letterSpacing: '-0.03em',
  },
  TextKRRegular12: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '18px',
    letterSpacing: '-0.03em',
  },
  TextKRRegular10: {
    fontFamily: 'Hyundai Sans Text KR,sans-serif',
    fontSize: '10px',
    fontWeight: 400,
    lineHeight: '16px',
    letterSpacing: '-0.03em',
  },

  DisplayText: {
    fontFamily: 'Hyundai Sans Head KR,sans-serif',
    fontSize: '146px',
    fontWeight: 700,
    lineHeight: '1.25',
    letterSpacing: '-0.03em',
  },
} as const;

export type TypographyType = typeof TYPOGRAPHY;
export type TypographyVariant = keyof TypographyType;
