name: gradle-CI

on:
  pull_request:
    branches: 'dev-be'

jobs:
  build:
    runs-on: ubuntu-latest
    env :
      working-directory : ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build
        working-directory : ${{ env.working-directory }}

      - name: Run Tests
        run: ./gradlew test
        working-directory : ${{ env.working-directory }}
